services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    image: mi-backend:1.0
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - mean-network

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile  # Asegúrate de que el archivo se llame así
    ports:
      - "4200:4200"  # Mapeamos el puerto 4200 del contenedor al puerto 4200 del host
    depends_on:
      - backend
    networks:
      - mean-network

networks:
  mean-network:
    driver: bridge