name: CI Backend Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: ⚡ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # MongoMemoryServer y Jest funcionan mejor con Node 20
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🛠 Cache MongoMemoryServer binaries
        uses: actions/cache@v3
        with:
          path: ~/.cache/mongodb-binaries
          key: ${{ runner.os }}-mongodb-binaries

      - name: Install backend dependencies
        working-directory: ./app/backend
        run: npm install

      - name: 🧪 Run backend tests with Jest
        working-directory: ./app/backend
        env:
          NODE_ENV: test
        run: |
          echo "Running tests..."
          npm test -- --runInBand --detectOpenHandles --forceExit --testTimeout=60000
